= Personal Blogging Project
:toc:
:toclevels: 5
jcayouette <joe.cayouette@gmail.com>

== Introduction

The goal of this project is to provide a place for daily knowledge to be stored,shared, discussed and distributed. 
It will act as a foundation for exploring and shaping various technical concepts and innovative solutions for many of my other projects.

This blog will eventually contain, thought experiments and insight exploring many fascinating topics such as: Information science, Christianity/Religous studies, both historical and observational science, diluvial geology/sedimentology, morality and ethics, philosophy, cosmology, business and project management and perhaps a few Greek, Hebrew, Latin, German, and English language studies and a smattering of various historical topics.

[quote, Jcayouette 2018]
____
**Disclaimer:** This project does not reflect or affiliate itself with the thoughts or opinions of any other corporate projects I am currently assocaited/aligned with. "Although some of the ideas presented here may wander into those projects, for example: IA for github pages, context based search, asciidoctor and jekyll." 
____

== Wiki - Planning and Contributor Guides

https://github.com/jcayouette/jcayouette-blog/wiki[Tech Stack and Contribution Guides]

== Planning Blog Infrastructure

=== Blog IA (Information Architecture)

JoAnn Hackos book - "Managing Your Documentation Projects" will be used to construct the plan for this blog. This will serve as a solid foundation to build the its structure, goals and process. I hope that by following her experience I will grow as a capable project manager. Big thanks to Lana Brindley for introducing me to this gem!

This blog will be a side project to my main profession so things will begin at a slow pace. Once planning, infrastructure, IA, and automation are in place, there should be at least semi-regular posts.
